### ISSUE TITLE
Error when creating rule for aggregation

### ISSUE THREAD

**Issue by timthee** [OpenAgenda/wordpress#35]
agenda/sources > "ajouter" > "ajouter une règle" > check "Définir des actions"

> Cannot read properties of undefined (reading 'fields')
    at Re (https://d1771xfuxsyp4n.cloudfront.net/aggSources-Dashboard.1e98fcf49e90371ae68a.js:1:20087)
    at div
    at div
    at d (https://d1771xfuxsyp4n.cloudfront.net/8728.c401b59f6957eab82574.js:2:23849)
    at div
    at Fe (https://d1771xfuxsyp4n.cloudfront.net/aggSources-Dashboard.1e98fcf49e90371ae68a.js:1:25596)
    at div
    at form
    at Ke (https://d1771xfuxsyp4n.cloudfront.net/aggSources-Dashboard.1e98fcf49e90371ae68a.js:1:34780)
    at E (https://d1771xfuxsyp4n.cloudfront.net/5924.78131e560b338665c27a.js:1:19386)
    at div
    at La (https://d1771xfuxsyp4n.cloudfront.net/aggSources-Dashboard.1e98fcf49e90371ae68a.js:1:64124)
    at div
    at section
    at div
    at v (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:157752)
    at Qa (https://d1771xfuxsyp4n.cloudfront.net/aggSources-Dashboard.1e98fcf49e90371ae68a.js:1:83521)
    at div
    at ns (https://d1771xfuxsyp4n.cloudfront.net/aggSources-Dashboard.1e98fcf49e90371ae68a.js:1:87952)
    at r (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:1183392)
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2360686)
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2362705)
    at div
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:42787)
    at https://d1771xfuxsyp4n.cloudfront.net/aggSources-App.52c37a0e7e5daa941947.js:1:364
    at r (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:1183392)
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2360686)
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2362705)
    at c (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2341530)
    at https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:199589
    at c (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:103832)
    at p (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:1243674)
    at div
    at div
    at div
    at q (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:108994)
    at c (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:103832)
    at A (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:104424)
    at c (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:103832)
    at a (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:119417)
    at c (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:103832)
    at p (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:1243674)
    at Ee (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:114714)
    at https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:93446
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:42787)
    at t.default (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:93777)
    at c (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2341530)
    at u (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2333811)
    at t.default (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:95159)
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2360686)
    at De (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:193741)
    at r (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2363242)
    at Ue (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:194840)
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2357343)
    at u (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2333811)
    at t (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:2232247)
    at t.default (https://d1771xfuxsyp4n.cloudfront.net/webapp.68a0ae227e570b939452.js:1:86066)
    at p (https://d1771xfuxsyp4n.cloudfront.net/2122.70f3b02a6d7c9eb233ea.js:2:1243674)

**Comment by kaore** [comment]
This is not a wordpress plugin issue. Send a mail to support@openagenda.com if this error persists.
